packages:
  - examples/*
  - packages/*
  - modules/*

onlyBuiltDependencies:
  - '@safe-fndn/safe-singleton-factory'
  - '@swc/core'
  - bufferutil
  - candide-contracts
  - es5-ext
  - esbuild
  - keccak
  - secp256k1
  - utf-8-validate
